adobe/aio-cli-plugin-console

.travis.yml, README.md, appveyor.yml, jest.setup.js, package.json
=> Added Travis CI and AppVeyor integrations

src/commands/console/select-integration.js, src/console-helpers.js, test/commands/console/select-integration.test.js
API change from the runtime api. 
Adobe JIRA ticket: RUNNER-1355
=> Add x-ims-org-id header to selectIntegrations call

README.md, src/commands/console/reset-integration.js, src/index.js, test/commands/console/reset-integration.test.js
=> Revoke wsk auth

package.json, src/commands/console/index.js, test/commands/console/index.test.js, test/commands/console/list-integrations.test.js, test/commands/console/reset-integration.test.js, test/commands/console/select-integration.test.js
=> Remove dependency on @adobe/oclif-base-index-command

src/commands/console/integration.js, src/commands/console/list-integrations.js, src/commands/console/reset-integration.js, src/commands/console/select-integration.js, src/commands/console/selected-integration.js
=> fix: add debug logging of caught errors for all commands

src/commands/console/reset-integration.js, src/commands/console/select-integration.js, src/console-helpers.js
=> ACNA-468 - Need `request` logging for `fetch`

src/commands/console/reset-integration.js, src/commands/console/select-integration.js, src/console-helpers.js, test/commands/console/reset-integration.test.js, test/console-helpers.js
Add Response logging (related #68)
=> feat: Add Response logging

src/commands/console/reset-integration.js, test/commands/console/reset-integration.test.js
=> ACNA-466 - aio console:reset XXXXX_YYYYY` results in 403 Forbidden

package.json
1.14.0 for @oclif/config is breaking the build. We'll have to push the investigation for later, for now we pin.
=> chore: pin @oclif/config to 1.13.3

package.json
=> chore: pin @oclif/command to 1.5.20

package.json
Closes #124
npm test
aio console:org:list (twice)
=> fix: running a command a second time, goes to IMS login again

e2e/e2e.js, jest.config.e2e.js, package.json
=> e2e test without user interaction

src/commands/console/project/list.js, src/commands/console/project/select.js, src/commands/console/workspace/download.js, src/commands/console/workspace/list.js, src/commands/console/workspace/select.js, test/__fixtures__/project/list-no-org.txt, test/__fixtures__/project/select-error.txt, test/__fixtures__/workspace/download-error1.txt, test/__fixtures__/workspace/download-error2.txt, test/__fixtures__/workspace/download-error3.txt, test/__fixtures__/workspace/list-error1.txt, test/__fixtures__/workspace/list-error2.txt, test/__fixtures__/workspace/select-error1.txt, test/__fixtures__/workspace/select-error2.txt, test/commands/console/workspace/download.test.js, test/commands/console/workspace/list.test.js, test/commands/console/workspace/select.test.js
=> unify missing selection error

README.md, src/commands/console/index.js, src/commands/console/org/select.js, test/commands/console/org/select.test.js
Fixes #136 
npm test
aio console:org:list
aio console:org:sel orgCode
=> fix: Org selection should use xxxxx@AdobeOrg instead of the short Adobe AMS Org

src/commands/console/index.js, src/commands/console/org/list.js, src/commands/console/org/select.js, src/commands/console/project/list.js, src/commands/console/project/select.js, src/commands/console/workspace/download.js, src/commands/console/workspace/list.js, src/commands/console/workspace/select.js, test/commands/console/org/list.test.js, test/commands/console/org/select.test.js, test/commands/console/project/list.test.js, test/commands/console/project/select.test.js, test/commands/console/workspace/download.test.js, test/commands/console/workspace/list.test.js, test/commands/console/workspace/select.test.js
add exitCode for failed selection calls that call printConsoleConfig
cleaned up tests
moved console api calls to BaseCommand
npm test
tested all aio console:* calls
=> fix: standardize format of command calls and error reporting

package.json, src/commands/console/index.js
=> rename $<config> to <config>

test/__fixtures__/org/list.txt, test/__fixtures__/project/list.txt, test/__fixtures__/workspace/list.txt
cli-ux@5.6.2  cli.table has new prettified output
Fixes #160 
npm test
=> fix: failing tests due to cli-ux@5.6.2

.github/workflows/node.js.yml, .github/workflows/on-push-publish-to-npm.yml, .github/workflows/version-bump-publish.yml, package.json
=> fix: @adobe/aio-lib-ims will require node-12 or greater starting July 14th, 2021

.github/workflows/daily.yml, .github/workflows/node.js.yml, .github/workflows/on-push-publish-to-npm.yml, .github/workflows/prerelease.yml, .github/workflows/version-bump-publish.yml
Implement reusable github workflows
[ACNA-1833](https://jira.corp.adobe.com/browse/ACNA-1833)
- Code Reusability
- Avoiding Redundancy
- This will be tested after PR is merged and deployed.
- This is workflow changes can only be tested post merge.
=> ACNA-1833 | Externalising github workflows

README.md, package.json
closes #212 
1. rm -rf node_modules
2. npm i
3. npm test
4. npm run prepack
5. Inspect README.md for `See code:` links (should point to the `.js` file)
=> fix: ACNA-2801 - code links in README point to a .ts file
